// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKHnbsaAF60mcU2eYDnVHUZr6tOlnzoqM',
    appId: '1:946761120019:web:230131f6c423a7406cc2e6',
    messagingSenderId: '946761120019',
    projectId: 'streamit-1-0',
    authDomain: 'streamit-1-0.firebaseapp.com',
    storageBucket: 'streamit-1-0.appspot.com',
    measurementId: 'G-P4G2HYZ1FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9LQ48IZnviiNt3Bi1-SP2luYHloQKD8',
    appId: '1:946761120019:android:f4325dd2ce1b410b6cc2e6',
    messagingSenderId: '946761120019',
    projectId: 'streamit-1-0',
    storageBucket: 'streamit-1-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3F30pzsKfBPuJI35pIhg2EyWWtELk8E',
    appId: '1:946761120019:ios:4c913f60bf87e6df6cc2e6',
    messagingSenderId: '946761120019',
    projectId: 'streamit-1-0',
    storageBucket: 'streamit-1-0.appspot.com',
    iosBundleId: 'com.manuraj.streamIt10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ3F30pzsKfBPuJI35pIhg2EyWWtELk8E',
    appId: '1:946761120019:ios:fa22159851d2a0936cc2e6',
    messagingSenderId: '946761120019',
    projectId: 'streamit-1-0',
    storageBucket: 'streamit-1-0.appspot.com',
    iosBundleId: 'com.manuraj.streamIt10.RunnerTests',
  );
}
